spring:
  application:
    name: wefin

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  flyway:
    enabled: true
    locations: classpath:db/migration

websocket:
  allowed-origins:
    - http://localhost:5173